chemical_aspirate_duration: 20
dispense_duration: 10
head:
  primer:
    analog_input: 0
    channel: 8
  quad1:
    analog_input: 1
    channel: 9
  quad2:
    analog_input: 2
    channel: 10
  quad3:
    analog_input: 3
    channel: 11
  quad4:
    analog_input: 4
    channel: 12
  quad5:
    analog_input: 5
    channel: 13
  quad6:
    analog_input: 6
    channel: 14
  system:
    channel: 15
load_duration: 20
manifold:
  aspirate:
    channel: 16
  red:
    channel: 17
  green:
    channel: 18
  yellow:
    channel: 19
  blue:
    channel: 20
  wash:
    channel: 21
prime_aspirate_duration: 5
prime_duration: 10
shake_speed_min: &shake_speed_min 200
shake_speed_max: &shake_speed_max 3000
protocol:
- chemical: wash
  dispense_count: 1
  shake_speed: *shake_speed_min
  shake_duration: 10
- chemical: red
  dispense_count: 1
  shake_speed: 400
  shake_duration: 3
- chemical: green
  dispense_count: 1
  shake_speed: null
  shake_duration: 10
- chemical: blue
  dispense_count: 1
  shake_speed: *shake_speed_min
  shake_duration: 0
- chemical: yellow
  dispense_count: 1
  shake_speed: *shake_speed_min
  shake_duration: 10
- chemical: wash
  dispense_count: 1
  shake_speed: 600
  shake_duration: 10
setup_duration: 20
