chemical_aspirate_duration: 20
dispense_duration: 5
head:
  primer:
    analog_input: 0
    channel: 8
  quad1:
    analog_input: 1
    channel: 9
  quad2:
    analog_input: 2
    channel: 10
  quad3:
    analog_input: 3
    channel: 11
  quad4:
    analog_input: 4
    channel: 12
  quad5:
    analog_input: 5
    channel: 13
  quad6:
    analog_input: 6
    channel: 14
  system:
    channel: 15
load_duration: 10
manifold:
  water1:
    channel: 16
  water2:
    channel: 17
  water3:
    channel: 18
  water4:
    channel: 19
  wash:
    channel: 20
  aspirate0:
    channel: 21
  aspirate1:
    channel: 22
prime_aspirate_duration: 5
prime_duration: 10
shake_speed_min: &shake_speed_min 200
shake_speed_max: &shake_speed_max 3000
protocol:
- chemical: wash
  dispense_count: 1
  shake_speed: *shake_speed_min
  shake_duration: 10
- chemical: water1
  dispense_count: 2
  shake_speed: 400
  shake_duration: 10
- chemical: water2
  dispense_count: 1
  shake_speed: null
  shake_duration: 10
- chemical: water3
  dispense_count: 1
  shake_speed: *shake_speed_min
  shake_duration: 0
- chemical: wash
  dispense_count: 1
  shake_speed: 600
  shake_duration: 10
setup_duration: 20
